#!/usr/bin/env bash
# This script manages 'manage_my_process'

# Define a function to start the process
start_process() {
  ./manage_my_process &
  touch /var/run/my_process.pid
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"
}

# Define a function to stop the process
stop_process() {
  echo "manage_my_process stopped"
  kill "$(cat /var/run/my_process.pid)"
  rm -f /var/run/my_process.pid
}

# Define a function to restart the process
restart_process() {
  stop_process
  start_process
  echo "manage_my_process restarted"
}

# Check the number of arguments
if [ $# -eq 0 ]
then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit 1
fi

# Use a case statement to handle different arguments
case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 2
    ;;
esac
