#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

for ((num=1; num<=100; num++))
do
  output=""
  if (( num % 3 == 0 )); then output+="Fizz"; fi
  if (( num % 5 == 0 )); then output+="Buzz"; fi
  if [[ -z $output ]]; then output=$num; fi
  echo "$output"
done
