#!/usr/bin/env bash
# This script tells a story based on the contents of the `/etc/passwd` file
myfile="/etc/passwd"
while IFS=: read -r user gang home ride place pass info
do
    echo "The user $user is part of the $gang gang, lives in $home and rides $ride. $place's place is protected by the passcode $pass, more info about the user here: $info"
done < "$myfile"
