#!/usr/bin/env bash
# A script that loops through 1 to 10 using while and prints a message based on the divisibility of the number

counter=1

while [ $counter -le 10 ]
do
    if [ $(($counter % 2)) -eq 0 ]
    then
        echo "even number"
    elif [ $(($counter % 3)) -eq 0 ]
    then
        echo "multiple of three"
    else
        echo "Wonderful School"
    fi
    ((counter++))
done
