#!/usr/bin/env bash
# A script that counts from 1 to 10 using while

num=1

while [ $num -le 10 ]
do
    if [ $num -eq 4 ]
    then
        echo "unlucky"
    elif [ $num -eq 8 ]
    then
        echo "lucky"
    else
        echo "Awesome School"
    fi
    ((num++))
done
