#!/usr/bin/env bash
# A script that uses a while loop to print different messages based on the value of i, which ranges from 1 to 10

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
