#!/usr/bin/env bash
# Prints numbers from 1 to 20 and also:
#   "bad luck from China" when the number is 4
#   "bad luck from Japan" when the number is 9
#   "bad luck from Italy" when the number is 17

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
