#!/usr/bin/env bash
# A script that prints the time in hours and minutes
# The hour ranges from 0 to 12
# The minute ranges from 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
