#!/bin/bash

# Get the PID of the Gunicorn master process
GUNICORN_PID=$(ps aux | grep 'gunicorn' | grep 'master' | awk '{print $2}')

# Send HUP signal to gracefully reload Gunicorn
if [ -n "$GUNICORN_PID" ]; then
    kill -HUP $GUNICORN_PID
    echo "Gunicorn has been reloaded gracefully."
else
    echo "Gunicorn master process not found."
fi
